name: journal_service
description: Service for managing journal entries.
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  dotenv: ^4.2.0
  drift: ^2.26.0
  drift_postgres: ^1.3.0
  fixnum: ^1.1.1
  grpc: ^4.0.4
  logger: ^2.5.0
  postgres: ^3.5.6
  protobuf: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  lints: ^4.0.0
  test: ^1.24.0
