name: journal_service
description: Service for managing journal entries.
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  grpc: ^4.0.1
  logger: ^2.5.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
