name: cbt_journal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  collection: ^1.18.0
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  firebase_ui_auth: ^1.16.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  form_field_validator: ^1.1.0
  go_router: ^14.8.1
  grpc: ^4.0.4
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  protobuf: ^4.0.0
  stack_board: ^0.2.6+1
  table_calendar: ^3.1.3
  uuid: ^4.5.1
  watch_it: ^1.6.2
  widgets_to_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.23.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
